### ISSUE TITLE
Mobile map position

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/chart-module-global-rate-map#19]
### Set the initial position of the map to centre window
![image](https://user-images.githubusercontent.com/7580745/91613285-d66f2680-e99c-11ea-9f45-3ab2a419ef5f.png)

### Look into a small y-overflow that makes the chart-div shift vertically on page scroll

**Comment by pkd2512** [comment]
![image](https://user-images.githubusercontent.com/7580745/91667410-21667680-eb22-11ea-84c7-7e7a1f39a6fa.png)

Map bottom crop on desktop

**Comment by gurmanbh** [comment]
Fixed in this [commit](https://github.com/reuters-graphics/newsapps_covid-global-tracker/commit/a5383c8a29e04d900d4b7847ab0289a94d8f00b9).
